# Generated by Django 3.2.6 on 2021-11-12 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_auto_20211112_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rate',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Оценка пользователя'),
        ),
    ]
