# Generated by Django 3.2.6 on 2021-11-12 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_review_enroll'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='enroll',
        ),
    ]
